package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/MicrosvcRepoEntryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

abstract public class MicrosvcRepoEntryHelper
{
  private static String  _id = "IDL:com/prismtech/agentv/core/types/MicrosvcRepoEntry:1.0";

  public static void insert (org.omg.CORBA.Any a, com.prismtech.agentv.core.types.MicrosvcRepoEntry that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.prismtech.agentv.core.types.MicrosvcRepoEntry extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nodeId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "microsvc",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.prismtech.agentv.core.types.MicrosvcRepoEntryHelper.id (), "MicrosvcRepoEntry", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.prismtech.agentv.core.types.MicrosvcRepoEntry read (org.omg.CORBA.portable.InputStream istream)
  {
    com.prismtech.agentv.core.types.MicrosvcRepoEntry value = new com.prismtech.agentv.core.types.MicrosvcRepoEntry ();
    value.nodeId = istream.read_string ();
    value.microsvc = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.prismtech.agentv.core.types.MicrosvcRepoEntry value)
  {
    ostream.write_string (value.nodeId);
    ostream.write_string (value.microsvc);
  }

}
