package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/MicrosvcRepoEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

/**
* Updated by idl2j
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "MicrosvcRepoEntry",
    keys = {"nodeId", "microsvc"}
)
public final class MicrosvcRepoEntry implements org.omg.CORBA.portable.IDLEntity
{
  public String nodeId = null;
  public String microsvc = null;

  public MicrosvcRepoEntry ()
  {
  } // ctor

  public MicrosvcRepoEntry (String _nodeId, String _microsvc)
  {
    nodeId = _nodeId;
    microsvc = _microsvc;
  } // ctor

} // class MicrosvcRepoEntry
