package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/MicrosvcActionKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public class MicrosvcActionKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.prismtech.agentv.core.types.MicrosvcActionKind[] __array = new com.prismtech.agentv.core.types.MicrosvcActionKind [__size];

  public static final int _A_START = 0;
  public static final com.prismtech.agentv.core.types.MicrosvcActionKind A_START = new com.prismtech.agentv.core.types.MicrosvcActionKind(_A_START);
  public static final int _A_STOP = 1;
  public static final com.prismtech.agentv.core.types.MicrosvcActionKind A_STOP = new com.prismtech.agentv.core.types.MicrosvcActionKind(_A_STOP);

  public int value ()
  {
    return __value;
  }

  public static com.prismtech.agentv.core.types.MicrosvcActionKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MicrosvcActionKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MicrosvcActionKind
