package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/MicrosvcActionCase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class MicrosvcActionCase implements org.omg.CORBA.portable.IDLEntity
{
  private com.prismtech.agentv.core.types.StartMicrosvc ___start;
  private com.prismtech.agentv.core.types.StopMicrosvc ___stop;
  private com.prismtech.agentv.core.types.MicrosvcActionKind __discriminator;
  private boolean __uninitialized = true;

  public MicrosvcActionCase ()
  {
  }

  public com.prismtech.agentv.core.types.MicrosvcActionKind discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public com.prismtech.agentv.core.types.StartMicrosvc start ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifystart (__discriminator);
    return ___start;
  }

  public void start (com.prismtech.agentv.core.types.StartMicrosvc value)
  {
    __discriminator = com.prismtech.agentv.core.types.MicrosvcActionKind.A_START;
    ___start = value;
    __uninitialized = false;
  }

  public void start (com.prismtech.agentv.core.types.MicrosvcActionKind discriminator, com.prismtech.agentv.core.types.StartMicrosvc value)
  {
    verifystart (discriminator);
    __discriminator = discriminator;
    ___start = value;
    __uninitialized = false;
  }

  private void verifystart (com.prismtech.agentv.core.types.MicrosvcActionKind discriminator)
  {
    if (discriminator != com.prismtech.agentv.core.types.MicrosvcActionKind.A_START)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.prismtech.agentv.core.types.StopMicrosvc stop ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifystop (__discriminator);
    return ___stop;
  }

  public void stop (com.prismtech.agentv.core.types.StopMicrosvc value)
  {
    __discriminator = com.prismtech.agentv.core.types.MicrosvcActionKind.A_STOP;
    ___stop = value;
    __uninitialized = false;
  }

  public void stop (com.prismtech.agentv.core.types.MicrosvcActionKind discriminator, com.prismtech.agentv.core.types.StopMicrosvc value)
  {
    verifystop (discriminator);
    __discriminator = discriminator;
    ___stop = value;
    __uninitialized = false;
  }

  private void verifystop (com.prismtech.agentv.core.types.MicrosvcActionKind discriminator)
  {
    if (discriminator != com.prismtech.agentv.core.types.MicrosvcActionKind.A_STOP)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class MicrosvcActionCase
