package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/NodeInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

/**
* Updated by idl2j
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "NodeInfo",
    keys = {"uuid"}
)
public final class NodeInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String uuid = null;
  public String info = null;

  public NodeInfo ()
  {
  } // ctor

  public NodeInfo (String _uuid, String _info)
  {
    uuid = _uuid;
    info = _info;
  } // ctor

} // class NodeInfo
