package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/NodeError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

/**
* Updated by idl2j
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "NodeError",
    keys = {"nodeId"}
)
public final class NodeError implements org.omg.CORBA.portable.IDLEntity
{
  public String nodeId = null;
  public short errno = (short)0;
  public String msg = null;

  public NodeError ()
  {
  } // ctor

  public NodeError (String _nodeId, short _errno, String _msg)
  {
    nodeId = _nodeId;
    errno = _errno;
    msg = _msg;
  } // ctor

} // class NodeError
