package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/RemoveMicrosvc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class RemoveMicrosvc implements org.omg.CORBA.portable.IDLEntity
{
  public String microsvc = null;

  public RemoveMicrosvc ()
  {
  } // ctor

  public RemoveMicrosvc (String _microsvc)
  {
    microsvc = _microsvc;
  } // ctor

} // class RemoveMicrosvc
