package com.prismtech.agentv.core.types;

/**
* com/prismtech/agentv/core/types/RepoActionCaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class RepoActionCaseHolder implements org.omg.CORBA.portable.Streamable
{
  public com.prismtech.agentv.core.types.RepoActionCase value = null;

  public RepoActionCaseHolder ()
  {
  }

  public RepoActionCaseHolder (com.prismtech.agentv.core.types.RepoActionCase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.prismtech.agentv.core.types.RepoActionCaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.prismtech.agentv.core.types.RepoActionCaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.prismtech.agentv.core.types.RepoActionCaseHelper.type ();
  }

}
