package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/RunningMicrosvc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

/**
* Updated by idl2j
* from ../idl/nodeinfo.idl
* Sunday, February 14, 2016 7:24:55 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "RunningMicrosvc",
    keys = {"nodeId", "microsvcId"}
)
public final class RunningMicrosvc implements org.omg.CORBA.portable.IDLEntity
{
  public String nodeId = null;
  public String microsvcId = null;

  // start action
  public String microsvc = null;

  public RunningMicrosvc ()
  {
  } // ctor

  public RunningMicrosvc (String _nodeId, String _microsvcId, String _microsvc)
  {
    nodeId = _nodeId;
    microsvcId = _microsvcId;
    microsvc = _microsvc;
  } // ctor

} // class RunningMicrosvc
