package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/StartMicrosvc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class StartMicrosvc implements org.omg.CORBA.portable.IDLEntity
{
  public String microsvc = null;
  public String microsvcId = null;

  // a UUID associated with this request
  public String args[] = null;

  public StartMicrosvc ()
  {
  } // ctor

  public StartMicrosvc (String _microsvc, String _microsvcId, String[] _args)
  {
    microsvc = _microsvc;
    microsvcId = _microsvcId;
    args = _args;
  } // ctor

} // class StartMicrosvc
