package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/StopMicrosvc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class StopMicrosvc implements org.omg.CORBA.portable.IDLEntity
{
  public String microsvcId = null;

  public StopMicrosvc ()
  {
  } // ctor

  public StopMicrosvc (String _microsvcId)
  {
    microsvcId = _microsvcId;
  } // ctor

} // class StopMicrosvc
