package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/UpgradeMicrosvc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

public final class UpgradeMicrosvc implements org.omg.CORBA.portable.IDLEntity
{
  public String microsvc = null;
  public boolean backup = false;
  public byte payload[] = null;

  public UpgradeMicrosvc ()
  {
  } // ctor

  public UpgradeMicrosvc (String _microsvc, boolean _backup, byte[] _payload)
  {
    microsvc = _microsvc;
    backup = _backup;
    payload = _payload;
  } // ctor

} // class UpgradeMicrosvc
