package com.prismtech.agentv.core.types;


/**
* com/prismtech/agentv/core/types/UpgradeMicrosvcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/actions.idl
* Sunday, February 14, 2016 7:24:59 PM CET
*/

abstract public class UpgradeMicrosvcHelper
{
  private static String  _id = "IDL:com/prismtech/agentv/core/types/UpgradeMicrosvc:1.0";

  public static void insert (org.omg.CORBA.Any a, com.prismtech.agentv.core.types.UpgradeMicrosvc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.prismtech.agentv.core.types.UpgradeMicrosvc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "microsvc",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "backup",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.prismtech.agentv.core.types.ByteSeqHelper.id (), "ByteSeq", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "payload",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.prismtech.agentv.core.types.UpgradeMicrosvcHelper.id (), "UpgradeMicrosvc", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.prismtech.agentv.core.types.UpgradeMicrosvc read (org.omg.CORBA.portable.InputStream istream)
  {
    com.prismtech.agentv.core.types.UpgradeMicrosvc value = new com.prismtech.agentv.core.types.UpgradeMicrosvc ();
    value.microsvc = istream.read_string ();
    value.backup = istream.read_boolean ();
    value.payload = com.prismtech.agentv.core.types.ByteSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.prismtech.agentv.core.types.UpgradeMicrosvc value)
  {
    ostream.write_string (value.microsvc);
    ostream.write_boolean (value.backup);
    com.prismtech.agentv.core.types.ByteSeqHelper.write (ostream, value.payload);
  }

}
