package com.prismtech.agentv.microsvc.daytime.types;


/**
* com/prismtech/agentv/microsvc/daytime/types/DayTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/types.idl
* Monday, February 15, 2016 10:36:23 AM CET
*/

/**
* Updated by idl2j
* from ../idl/types.idl
* Monday, February 15, 2016 10:36:23 AM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "DayTime",
    keys = {}
)
public final class DayTime implements org.omg.CORBA.portable.IDLEntity
{
  public long currentTimeMillis = (long)0;
  public long nanoTime = (long)0;

  public DayTime ()
  {
  } // ctor

  public DayTime (long _currentTimeMillis, long _nanoTime)
  {
    currentTimeMillis = _currentTimeMillis;
    nanoTime = _nanoTime;
  } // ctor

} // class DayTime
