package com.prismtech.agentv.microsvc.daytime.types;

/**
* com/prismtech/agentv/microsvc/daytime/types/DayTimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/types.idl
* Monday, February 15, 2016 10:36:23 AM CET
*/

public final class DayTimeHolder implements org.omg.CORBA.portable.Streamable
{
  public com.prismtech.agentv.microsvc.daytime.types.DayTime value = null;

  public DayTimeHolder ()
  {
  }

  public DayTimeHolder (com.prismtech.agentv.microsvc.daytime.types.DayTime initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.prismtech.agentv.microsvc.daytime.types.DayTimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.prismtech.agentv.microsvc.daytime.types.DayTimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.prismtech.agentv.microsvc.daytime.types.DayTimeHelper.type ();
  }

}
