#!/bin/bash

CORE_ASSEMBLIES="agentv agentv-runtime agentv-commander"

sbt publish-local

for asb in ${CORE_ASSEMBLIES}
do
    pushd $PWD &>/dev/null
    cd ${asb}
    sbt assembly
    popd &>/dev/null
done
